<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Блоги");
\Bitrix\Main\Loader::includeModule('richsite.fashi');
$settings=new Richsite\Fashi\Settings;
?><section class="blog-section spad">
<div class="container">
	<div class="row">
		 <?$APPLICATION->IncludeComponent(
	"bitrix:blog",
	"",
	Array(
		"AJAX_POST" => "Y",
		"ALLOW_POST_CODE" => "Y",
		"ALLOW_POST_MOVE" => "Y",
		"BLOG_COUNT" => "20",
		"BLOG_COUNT_MAIN" => "6",
		"BLOG_PROPERTY" => array(),
		"BLOG_PROPERTY_LIST" => array(),
		"CACHE_TIME" => "3600",
		"CACHE_TIME_LONG" => "604800",
		"CACHE_TYPE" => "A",
		"COLOR_TYPE" => "Y",
		"COMMENTS_COUNT" => "25",
		"COMMENT_ALLOW_IMAGE_UPLOAD" => "A",
		"COMMENT_ALLOW_VIDEO" => "Y",
		"COMMENT_EDITOR_CODE_DEFAULT" => "Y",
		"COMMENT_EDITOR_DEFAULT_HEIGHT" => "200",
		"COMMENT_EDITOR_RESIZABLE" => "Y",
		"COMMENT_PROPERTY" => array(),
		"DATE_TIME_FORMAT" => "d.m.Y H:i:s",
		"EDITOR_CODE_DEFAULT" => "N",
		"EDITOR_DEFAULT_HEIGHT" => "300",
		"EDITOR_RESIZABLE" => "Y",
		"GROUP_ID" => array("1"),
		"IMAGE_MAX_HEIGHT" => "800",
		"IMAGE_MAX_WIDTH" => "800",
		"MESSAGE_COUNT" => "25",
		"MESSAGE_COUNT_MAIN" => "6",
		"MESSAGE_LENGTH" => "100",
		"NAME_TEMPLATE" => "#NOBR##LAST_NAME# #NAME##/NOBR#",
		"NAV_TEMPLATE" => "",
		"NOT_USE_COMMENT_TITLE" => "Y",
		"NO_URL_IN_COMMENTS_AUTHORITY" => "",
		"PATH_TO_GROUP_BLOG" => "",
		"PATH_TO_GROUP_DRAFT" => "",
		"PATH_TO_GROUP_POST" => "",
		"PATH_TO_GROUP_POST_EDIT" => "",
		"PATH_TO_MESSAGES_CHAT" => "/club/messages/chat/#user_id#/",
		"PATH_TO_SMILE" => "/bitrix/images/blog/smile/",
		"PATH_TO_SONET_USER_PROFILE" => "/club/user/#user_id#/",
		"PATH_TO_USER_BLOG" => "",
		"PATH_TO_USER_DRAFT" => "",
		"PATH_TO_USER_POST" => "",
		"PATH_TO_USER_POST_EDIT" => "",
		"PERIOD" => "",
		"PERIOD_DAYS" => "30",
		"PERIOD_NEW_TAGS" => "",
		"POST_PROPERTY" => array(),
		"POST_PROPERTY_LIST" => array(),
		"SEF_FOLDER" => "/blog/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => Array("index"=>"index.php","group"=>"group/#group_id#/","blog"=>"#blog#/","user"=>"user/#user_id#/","user_friends"=>"friends/#user_id#/","search"=>"search.php","user_settings"=>"#blog#/user_settings.php","user_settings_edit"=>"#blog#/user_settings_edit.php?id=#user_id#","group_edit"=>"#blog#/group_edit.php","blog_edit"=>"#blog#/blog_edit.php","category_edit"=>"#blog#/category_edit.php","post_edit"=>"#blog#/post_edit.php?id=#post_id#","draft"=>"#blog#/draft.php","moderation"=>"#blog#/moderation.php","trackback"=>POST_FORM_ACTION_URI.'&blog=#blog#&id=#post_id#&page=trackback',"post"=>"#blog#/#post_id#/","post_rss"=>"#blog#/rss/#type#/#post_id#","rss"=>"#blog#/rss/#type#","rss_all"=>"rss/#type#/#group_id#"),
		"SEO_USE" => "N",
		"SEO_USER" => "Y",
		"SET_NAV_CHAIN" => "Y",
		"SET_TITLE" => "Y",
		"SHARE_HANDLERS" => array("delicious","facebook","lj","twitter"),
		"SHARE_HIDE" => "Y",
		"SHARE_SHORTEN_URL_KEY" => "",
		"SHARE_SHORTEN_URL_LOGIN" => "",
		"SHARE_TEMPLATE" => "",
		"SHOW_LOGIN" => "Y",
		"SHOW_NAVIGATION" => "N",
		"SHOW_SPAM" => "Y",
		"SMILES_COUNT" => "4",
		"THEME" => "blue",
		"USER_PROPERTY" => array(),
		"USER_PROPERTY_NAME" => "",
		"USE_ASC_PAGING" => "N",
		"USE_GOOGLE_CODE" => "Y",
		"USE_SHARE" => "Y",
		"VARIABLE_ALIASES" => Array("index"=>Array(),"group"=>Array(),"blog"=>Array(),"user"=>Array(),"user_friends"=>Array(),"search"=>Array(),"user_settings"=>Array(),"user_settings_edit"=>Array("user_id"=>"id"),"group_edit"=>Array(),"blog_edit"=>Array(),"category_edit"=>Array(),"post_edit"=>Array("post_id"=>"id"),"draft"=>Array(),"moderation"=>Array(),"trackback"=>Array("blog"=>"blog","post_id"=>"id"),"post"=>Array(),"post_rss"=>Array(),"rss"=>Array(),"rss_all"=>Array(),),
		"WIDTH" => "100%"
	)
);?>
	</div>
</div>
 </section><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php")?>